[plugins]
hytalegradle = { id = "app.ultradev.hytalegradle", version = "2.0.2" }
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version = "1.3" }
shadow = { id = "com.gradleup.shadow", version = "9.3.1" }

[libraries]
jsoup = { group = "org.jsoup", name = "jsoup", version = "1.22.1" }
junit = { group = "org.junit.jupiter", name = "junit-jupiter", version = "6.0.2" }
junit-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
